apiVersion: 1

datasources:

  - name: Mimir
    uid: lgtm-mimir
    type: prometheus
    url: http://mimir:9009/prometheus
    access: proxy
    editable: true
    isDefault: false

  - name: Loki
    uid: lgtm-loki
    type: loki
    url: http://loki:3100
    access: proxy
    editable: true
    isDefault: false

  - name: Tempo
    uid: lgtm-tempo
    type: tempo
    url: http://tempo:3200
    access: proxy
    editable: true
    isDefault: false
